### ISSUE TITLE
Property 'TwitterCompose' is misspelled or does not exist.

### ISSUE THREAD

**Issue by ege-ah** [twitter/compose-rules#100]
When the detektPlugin applied and rules added to the config file, CI build fails with error

**Run failed with 1 invalid config property.   	- Property 'TwitterCompose' is misspelled or does not exist.**

**To Reproduce**
1. Apply plugin 

```
dependencies {
            detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:$detektVersion")
            detektPlugins("com.twitter.compose.rules:detekt:$twitterComposeVersion")
        }
```
2. Add compose rules to bottom of the existing `detekt-config.xml`

```
TwitterCompose:
  CompositionLocalAllowlist:
    active: true
    # You can optionally define a list of CompositionLocals that are allowed here
    # allowedCompositionLocals: LocalSomething,LocalSomethingElse
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  ModifierComposable:
    active: true
  ModifierMissing:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  MutableParams:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  PreviewNaming:
    active: true
  PreviewPublic:
    active: false
  RememberMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
```

3. Run ./gradlew sonarqube

**Expected behavior**
Project compiles and CI build success

Instead it is failing on CI and locally, note that current detekt setup is working properly after deleting the TwitterCompose rule set.

**Environment**
Version 1.21

```
* What went wrong:
Execution failed for task ':sonarqube'.
> Run failed with 1 invalid config property.
  	- Property 'TwitterCompose' is misspelled or does not exist.
```
