### ISSUE TITLE
ComposableNaming is not configurable in Detekt

### ISSUE THREAD

**Issue by ZacSweers** [twitter/compose-rules#107]
This is a followup from #104

I've tried all of these different configurations for the new functionality and none of them appear to work. It seems to me that this rule is somehow not configurable in its release. Did I miss something in my PR?

```yml
TwitterCompose:
  # Not top level
  allowedComposableFunctionNames: ['.*Presenter']
  # ComposeNaming and ComposableNaming are both used, so tried configuring both without success
  ComposeNaming:
    active: true
    allowedComposableFunctionNames: ['.*Presenter']
  ComposableNaming:
    active: true
    allowedComposableFunctionNames: ['.*Presenter']
```

Repro: https://github.com/slackhq/circuit/pull/225
